/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jflk;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/**
 *
 * @author aluno
 */
public class JFLK extends javax.swing.JFrame {

    Date dataNascimento = null;
    int idade;
    
    int calcIdade(){
        Calendar dataNasc = Calendar.getInstance();
        dataNasc.setTime(dataNascimento);
        Calendar hoje = Calendar.getInstance();
        hoje.getTime();
        idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);
        dataNasc.add(Calendar.YEAR, idade);
        if(hoje.before(dataNasc)){
        idade--;       
        }
        return idade;
    }
    public JFLK() {
        initComponents();
        lblresponsavel.setVisible(false);
        lblresp.setVisible(false);
        txtresponsavel.setVisible(false);
        imprimir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        test = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cadastro = new javax.swing.JPanel();
        txtserie = new javax.swing.JTextField();
        txtresponsavel = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtnascimento = new javax.swing.JFormattedTextField();
        cadastrar = new javax.swing.JButton();
        informatica = new javax.swing.JRadioButton();
        eletrotecnica = new javax.swing.JRadioButton();
        quimica = new javax.swing.JRadioButton();
        geologia = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblresp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtno = new javax.swing.JLabel();
        txtdata = new javax.swing.JLabel();
        txtser = new javax.swing.JLabel();
        txtcur = new javax.swing.JLabel();
        txtrep = new javax.swing.JLabel();
        imprimir = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lblresponsavel = new javax.swing.JLabel();
        lblserie = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        lblnascimento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbresponsa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        lblnome1 = new javax.swing.JLabel();
        lblnome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        test.setBackground(new java.awt.Color(238, 205, 175));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Desktop\\WhatsApp Image 2024-03-27 at 11.45.46.jpeg")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(400, 500));
        jLabel11.setMinimumSize(new java.awt.Dimension(400, 500));
        jLabel11.setPreferredSize(new java.awt.Dimension(400, 500));

        cadastro.setBackground(new java.awt.Color(234, 206, 177));
        cadastro.setPreferredSize(new java.awt.Dimension(500, 500));

        txtserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserieActionPerformed(evt);
            }
        });

        txtresponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresponsavelActionPerformed(evt);
            }
        });

        try {
            txtnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtnascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnascimentoFocusLost(evt);
            }
        });
        txtnascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnascimentoActionPerformed(evt);
            }
        });

        cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        informatica.setBackground(new java.awt.Color(234, 206, 177));
        buttonGroup1.add(informatica);
        informatica.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        informatica.setText("INFORMÁTICA");

        eletrotecnica.setBackground(new java.awt.Color(234, 206, 177));
        buttonGroup1.add(eletrotecnica);
        eletrotecnica.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        eletrotecnica.setText("ELETROTÉCNICA");
        eletrotecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletrotecnicaActionPerformed(evt);
            }
        });

        quimica.setBackground(new java.awt.Color(234, 206, 177));
        buttonGroup1.add(quimica);
        quimica.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        quimica.setText("QUÍMICA");
        quimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quimicaActionPerformed(evt);
            }
        });

        geologia.setBackground(new java.awt.Color(234, 206, 177));
        buttonGroup1.add(geologia);
        geologia.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        geologia.setText("GEOLOGIA");

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("NOME:");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("DATA DE NASCIMENTO:");

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("SÉRIE:");

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("CURSO:");

        lblresp.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblresp.setText("NOME DO RESPONSÁVEL:");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 0, 1));
        jLabel5.setText("CADASTRAR");

        javax.swing.GroupLayout cadastroLayout = new javax.swing.GroupLayout(cadastro);
        cadastro.setLayout(cadastroLayout);
        cadastroLayout.setHorizontalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cadastroLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(txtser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(txtrep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cadastroLayout.createSequentialGroup()
                                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cadastroLayout.createSequentialGroup()
                                            .addComponent(txtnascimento)
                                            .addGap(18, 18, 18))
                                        .addGroup(cadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(45, 45, 45)))
                                    .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblresp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(cadastroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcur, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eletrotecnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(informatica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geologia)
                            .addComponent(quimica))
                        .addGap(94, 94, 94))))
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5))
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(cadastrar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtresponsavel)
                .addContainerGap())
        );
        cadastroLayout.setVerticalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geologia)
                    .addComponent(informatica))
                .addGap(18, 18, 18)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quimica)
                    .addComponent(eletrotecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtrep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout testLayout = new javax.swing.GroupLayout(test);
        test.setLayout(testLayout);
        testLayout.setHorizontalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        testLayout.setVerticalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testLayout.createSequentialGroup()
                .addGroup(testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        imprimir.setBackground(new java.awt.Color(234, 206, 177));

        lblnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnome.setText("                                                                           ");

        lblresponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblresponsavel.setText("                                                                   ");

        lblserie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblserie.setText("                         ");

        lblcurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcurso.setText("                  ");

        lblnascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnascimento.setText("                             ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("NOME:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("DATA DE NASCIMENTO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("SÉRIE:");

        lbresponsa.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbresponsa.setText("NOME DO RESPONSÁVEL:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("CURSO:");

        voltar.setBackground(new java.awt.Color(255, 255, 255));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        lblnome1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblnome1.setText("Miserável! Você está cadastrado(a)");

        lblnome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnome2.setText("                                                                           ");

        javax.swing.GroupLayout imprimirLayout = new javax.swing.GroupLayout(imprimir);
        imprimir.setLayout(imprimirLayout);
        imprimirLayout.setHorizontalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imprimirLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblserie))
                            .addGroup(imprimirLayout.createSequentialGroup()
                                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imprimirLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblnascimento))
                                    .addGroup(imprimirLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblnome)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblnome2))))
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcurso))
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addComponent(lbresponsa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblresponsavel)))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirLayout.createSequentialGroup()
                        .addComponent(lblnome1)
                        .addGap(242, 242, 242))))
        );
        imprimirLayout.setVerticalGroup(
            imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblnome1)
                .addGap(42, 42, 42)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblnascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblserie))
                .addGap(4, 4, 4)
                .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(voltar))
                    .addGroup(imprimirLayout.createSequentialGroup()
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblcurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbresponsa)
                            .addComponent(lblresponsavel))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        
        String name = txtnome.getText();
        String year = txtnascimento.getText();
        String ano = txtserie.getText();
        String curso = "";
        if (eletrotecnica.isSelected()) {
            curso = eletrotecnica.getText();
        }
        if (informatica.isSelected()) {
            curso = informatica.getText();
        }
        if (geologia.isSelected()) {
            curso = geologia.getText();
        }
        if (quimica.isSelected()) {
            curso = quimica.getText();
        }
        String responsavel = txtresponsavel.getText();
        
        if(name.isEmpty() || year.isEmpty() || ano.isEmpty() || curso.isEmpty() || responsavel.isEmpty()){
            if (name.isEmpty()) {
                txtno.setText("Informe o nome!");
            }
            if (year.isEmpty()) {
                txtdata.setText("Informe a data de nascimento!");
            }
            if (ano.isEmpty()) {
                txtser.setText("Informe o ano!");
            }
            if (curso.isEmpty()) {
                txtcur.setText("Informe o curso!");
            }
            if (responsavel.isEmpty()&& idade < 18 && (!(year.isEmpty()))) {
                txtrep.setVisible(true);
                txtrep.setText("Informe o responsavel!");
            } 
        } 
        else {
            lblnome.setText(name);
            lblnascimento.setText(year);
            lblserie.setText(ano);
            if (eletrotecnica.isSelected()) {
                curso = eletrotecnica.getText();
                lblcurso.setText(curso);
            }
            if (informatica.isSelected()) {
                curso = informatica.getText();
                lblcurso.setText(curso);
            }
            if (geologia.isSelected()) {
                curso = geologia.getText();
                lblcurso.setText(curso);
            }
            if (quimica.isSelected()) {
                curso = quimica.getText();
                lblcurso.setText(curso);
            }
            lblresponsavel.setText(responsavel);
            cadastro.setVisible(false);
            imprimir.setVisible(true);
            test.setVisible(true);
        }
       
    }//GEN-LAST:event_cadastrarActionPerformed

    private void txtnascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnascimentoActionPerformed

    private void txtnascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnascimentoFocusLost
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);;
        try {
            dataNascimento = formatoData.parse(txtnascimento.getText());
            idade = calcIdade();
            System.out.println(idade);
            if (idade < 18) {
                lblresponsavel.setVisible(true);
                txtresponsavel.setVisible(true);
                lbresponsa.setVisible(true);
                lblresp.setVisible(true);
            } else {
                lblresponsavel.setVisible(false);
                txtresponsavel.setVisible(false);
                lbresponsa.setVisible(false);
                lblresp.setVisible(false);
            }
        } catch (Exception e) {
            System.out.println("Data Inválida!");
        }
        
        
    }//GEN-LAST:event_txtnascimentoFocusLost

    private void txtserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieActionPerformed

    private void txtresponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresponsavelActionPerformed

    private void quimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quimicaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        cadastro.setVisible(true);
        imprimir.setVisible(false);
        txtnome.setText(" ");
        txtserie.setText(" ");
        txtresponsavel.setText(" ");
        txtnascimento.setText(null);
        txtno.setText(" ");
        txtser.setText(" ");
        txtdata.setText(" ");
        txtcur.setText(" ");
        txtrep.setText(" ");
        buttonGroup1.clearSelection();
          if(idade<18){
           lblresp.setVisible(false);
           txtresponsavel.setVisible(false);
       }
       
    }//GEN-LAST:event_voltarActionPerformed

    private void eletrotecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletrotecnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eletrotecnicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastrar;
    private javax.swing.JPanel cadastro;
    private javax.swing.JRadioButton eletrotecnica;
    private javax.swing.JRadioButton geologia;
    private javax.swing.JPanel imprimir;
    private javax.swing.JRadioButton informatica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblnascimento;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblnome1;
    private javax.swing.JLabel lblnome2;
    private javax.swing.JLabel lblresp;
    private javax.swing.JLabel lblresponsavel;
    private javax.swing.JLabel lblserie;
    private javax.swing.JLabel lbresponsa;
    private javax.swing.JRadioButton quimica;
    private javax.swing.JPanel test;
    private javax.swing.JLabel txtcur;
    private javax.swing.JLabel txtdata;
    private javax.swing.JFormattedTextField txtnascimento;
    private javax.swing.JLabel txtno;
    private javax.swing.JTextField txtnome;
    private javax.swing.JLabel txtrep;
    private javax.swing.JTextField txtresponsavel;
    private javax.swing.JLabel txtser;
    private javax.swing.JTextField txtserie;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
